/**
 * Basic usage example for the Markdown Export SDK
 *
 * Run with: npx tsx examples/basic-usage.ts
 */

import { writeFile } from 'fs/promises';
import {
  convert,
  convertToHtml,
  convertToPdf,
  convertToDocx,
  registerTemplate,
} from '../src/index.js';

async function main() {
  // Sample document
  const document = `
# Quarterly Report Q4 2024

## Executive Summary

This report summarizes the key achievements and metrics for Q4 2024.
Our team has made significant progress across all major initiatives.

## Key Metrics

- Revenue: $1.2M (+15% YoY)
- Active Users: 50,000 (+20% QoQ)
- Customer Satisfaction: 4.8/5.0

## Highlights

### Product Development

1. Launched new dashboard feature
2. Improved API response times by 40%
3. Added 5 new integrations

### Team Growth

We welcomed 10 new team members this quarter:

- 4 Engineers
- 3 Product Managers
- 2 Designers
- 1 Data Analyst

## Technical Updates

Here's an example of our new API endpoint:

\`\`\`javascript
const response = await fetch('/api/v2/metrics', {
  headers: { 'Authorization': 'Bearer token' }
});
const data = await response.json();
\`\`\`

## Looking Ahead

> Our focus for Q1 2025 will be on scaling our infrastructure
> and expanding into new markets.

---

*Report generated by Markdown Export SDK*
`;

  const metadata = {
    title: 'Quarterly Report Q4 2024',
    author: 'Business Analytics Team',
    date: '2024-12-31',
    description: 'Q4 2024 quarterly business report',
    keywords: ['quarterly', 'report', 'Q4', '2024', 'business'],
  };

  console.log('Markdown Export SDK - Basic Usage Example\n');
  console.log('=========================================\n');

  // Example 1: Convert to all formats at once
  console.log('1. Converting to all formats...');
  const allFormats = await convert(document, {
    format: ['md', 'html', 'pdf', 'docx'],
    metadata,
  });

  await writeFile('output-all.md', allFormats.md!);
  await writeFile('output-all.html', allFormats.html!);
  await writeFile('output-all.pdf', allFormats.pdf!);
  await writeFile('output-all.docx', allFormats.docx!);
  console.log('   ✓ Created output-all.md, output-all.html, output-all.pdf, output-all.docx\n');

  // Example 2: Convert to single format using convenience functions
  console.log('2. Using convenience functions...');

  const html = await convertToHtml(document, { metadata });
  await writeFile('output-html.html', html);
  console.log('   ✓ Created output-html.html');

  const pdf = await convertToPdf(document, { metadata });
  await writeFile('output-pdf.pdf', pdf);
  console.log('   ✓ Created output-pdf.pdf');

  const docx = await convertToDocx(document, { metadata });
  await writeFile('output-docx.docx', docx);
  console.log('   ✓ Created output-docx.docx\n');

  // Example 3: Convert plain text (not markdown)
  console.log('3. Converting plain text...');
  const plainText = `
Meeting Notes - December 15, 2024

Attendees: Alice, Bob, Charlie

Discussion Points:
• Budget review for Q1
• New project timeline
• Team restructuring proposal

Action Items:
1. Alice to prepare budget presentation
2. Bob to draft project milestones
3. Charlie to schedule follow-up meeting

Next meeting: January 5, 2025
`;

  const plainResult = await convert(plainText, {
    format: ['md', 'html'],
    metadata: { title: 'Meeting Notes' },
  });

  await writeFile('output-plain.md', plainResult.md!);
  await writeFile('output-plain.html', plainResult.html!);
  console.log('   ✓ Created output-plain.md, output-plain.html\n');

  // Example 4: Minimal conversion (no metadata)
  console.log('4. Minimal conversion...');
  const minimal = await convert('# Hello World\n\nThis is a simple test.', {
    format: ['html'],
  });
  await writeFile('output-minimal.html', minimal.html!);
  console.log('   ✓ Created output-minimal.html\n');

  console.log('=========================================');
  console.log('All examples completed successfully!');
  console.log('\nGenerated files:');
  console.log('  - output-all.md');
  console.log('  - output-all.html');
  console.log('  - output-all.pdf');
  console.log('  - output-all.docx');
  console.log('  - output-html.html');
  console.log('  - output-pdf.pdf');
  console.log('  - output-docx.docx');
  console.log('  - output-plain.md');
  console.log('  - output-plain.html');
  console.log('  - output-minimal.html');
}

main().catch(console.error);
